### ISSUE TITLE
How do I run the code?

### ISSUE THREAD

**Issue by StickyBoy321** [smourier/IsWindowsPlayingSound#1]
@smourier   
How do I run the code? I opened it in visual studio code and tried to run it but nothing was outputted in the terminal in the bottom. 
Sorry I've never really coded anything before so I don't know what to do.

![Screenshot 2021-09-02 021956](https://user-images.githubusercontent.com/89932458/131766476-9f50e505-9cd5-4be7-9e24-546d53834123.png)

**Comment by smourier** [comment]
The project is made for Visual Studio (2019), not for Visual Studio Code. But it could be adapted.

Otherwise, if you want to try it just download the already built release .exe

**Comment by StickyBoy321** [comment]
Sorry where would I find the .exe?

**Comment by smourier** [comment]
https://github.com/smourier/IsWindowsPlayingSound/releases

**Comment by StickyBoy321** [comment]
I tried to open the exe (by double clicking on it) but it opens then immediately closes

**Comment by smourier** [comment]
This is a command line tool, so run it in a command line box (cmd.exe) or run it like "IsWindowsPlayingSound.exe loop" to make it loop infinitely
