### ISSUE TITLE
Trigger by Audio Input

### ISSUE THREAD

**Issue by dhess83** [smourier/IsWindowsPlayingSound#2]
Hi! Thank you for writing this application.  I was wondering if you could tell me how to modify it to see if an audio INPUT device is receiving audio.  I have a Line-Input that connects to a music device, and I would like to execute a script when the device beings playing audio through the PC's line-input device.  I can compile your code in Visual Studio, but I must admit I don't understand it.  Any help you could provide would be greatly appreciated.

P.S. This is for a non-commercial use, for my home audio.

**Comment by smourier** [comment]
Hi,

Do you mean like for example you would detect someone is speaking (sound) into a microphone (input)? This is completely different as this program is about output, not input.

**Comment by smourier** [comment]
Closed du to inactivity
