### ISSUE TITLE
detecting multi sound devices

### ISSUE THREAD

**Issue by shirubei** [smourier/IsWindowsPlayingSound#3]
Thanks for providing this compact tools. 
It really help a lot.
Just wonder if it can detect which device is playing when there's multi sound devices in the system.

**Comment by smourier** [comment]
Hi,

No, it just displays the peak sample value for the channels in the "default audio end point" (for rendering) as you can see in the code here https://github.com/smourier/IsWindowsPlayingSound/blob/master/IsWindowsPlayingSound/IsWindowsPlayingSound.cpp#L41C23-L41C46

The code could be changed to enumerate all endpoints using IMMDeviceEnumerator::EnumAudioEndpoints method https://learn.microsoft.com/en-us/windows/win32/api/mmdeviceapi/nf-mmdeviceapi-immdeviceenumerator-enumaudioendpoints

**Comment by shirubei** [comment]
I got it.
Thanks a lot.
